disabled: false
field_template: false
ft-default: default
ft-show-colon: false
classes:
  region:
    - 'blockquote_first_column|Blockquote First Column'
    - 'blockquote_second_column|Blockquote Second Column'
    - 'statistic_first_column|Statistic First Column'
    - 'statistic_second_column|Statistic Second Column'
  field: {  }
use_field_names: true
_core:
  default_config_hash: xfB0qOeoAomOThclNNokdKTrVwXLcXz13SU3-4a5-FY
