entity_type_groups:
  node:
    area_of_study:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    article:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    case_study:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    course:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    event:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    find_your_fit:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    marketing_landing_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    owned_program_interior_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    owned_program_landing_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    person:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    story:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
