entity_type_groups:
  node:
    area_of_study:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    article:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    case_study:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    course:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    find_your_fit:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    non_owned_program_landing_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    owned_program_interior_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    owned_program_landing_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    person:
      basic: basic
      advanced: advanced
    story:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
