schemas:
  bootstrap: 8000
  ucpe_theme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/custom/ucpe_theme/favicon.ico
  url: 'http://localhost:32774/themes/custom/ucpe_theme/favicon.ico'
  use_default: false
table_responsive: '-1'
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
button_size: btn-sm
